# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0ad0c4e564080ee9800179ea498b4da4f85026d1078ef19aa147f7217713bbf56b8f1b5075298776cb79910b8976332eee65b606b99ca1b21e0a8e1ec07bb730

test:
  secret_key_base: 20f01ce46d5ea36c0f8465f93827aaf4f0a4d9d4ef2be9c84c826556348c3a750e0f256f75eef26979b563da2238b4d911337756a2c0ba261eea8a27b50f7033

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
